import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';
import prettierConfig from 'eslint-config-prettier';
import importPlugin from 'eslint-plugin-import';
import tseslint from 'typescript-eslint';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

export default tseslint.config(
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'drizzle/**',
      'playwright-report/**',
      'coverage/**',
      // Generated by `next build`; it references .next/types with a triple-slash path.
      'next-env.d.ts',
    ],
  },
  ...compat.extends('next/core-web-vitals'),
  ...tseslint.configs.recommendedTypeChecked,
  {
    languageOptions: {
      parserOptions: {
        projectService: { allowDefaultProject: ['eslint.config.mjs', 'postcss.config.mjs'] },
        tsconfigRootDir: import.meta.dirname,
      },
    },
    plugins: { import: importPlugin },
    rules: {
      'import/order': [
        'error',
        {
          groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
          'newlines-between': 'never',
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],
      '@typescript-eslint/no-explicit-any': 'error',
      // `interface Tx extends KycMutations {}` is the per-app mutation merge point: apps add
      // themselves to the extends clause, so a single extend with no members is deliberate.
      '@typescript-eslint/no-empty-object-type': [
        'error',
        { allowInterfaces: 'with-single-extends' },
      ],
      '@typescript-eslint/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/no-misused-promises': ['error', { checksVoidReturn: false }],
      // Async without await is normal here: mocks and test doubles satisfy async interfaces.
      '@typescript-eslint/require-await': 'off',
    },
  },
  {
    // Convention 1: every domain mutation goes through audited(). The Drizzle client is only
    // reachable from the db, audit and auth (session rows) modules, so writes to business
    // entities cannot bypass the wrapper.
    files: ['src/**/*.{ts,tsx}'],
    ignores: [
      'src/lib/db/**',
      'src/lib/audit/**',
      'src/lib/auth/**',
      'src/test/**',
      '**/*.test.ts',
    ],
    rules: {
      'no-restricted-imports': [
        'error',
        {
          paths: [
            {
              name: '@/lib/db/client',
              message:
                'Do not use the Drizzle client directly. Mutate through audited() in @/lib/audit and read through accessors in @/lib/db.',
            },
          ],
        },
      ],
    },
  },
  {
    // eslint-plugin-import ships no types, so the plugin object is `error`-typed here.
    files: ['eslint.config.mjs'],
    rules: { '@typescript-eslint/no-unsafe-assignment': 'off' },
  },
  {
    files: ['**/*.test.ts', 'e2e/**/*.ts', 'src/test/**/*.ts'],
    rules: { '@typescript-eslint/no-non-null-assertion': 'off' },
  },
  prettierConfig,
);
